version: '3.8'

services:
  gg-fonts-clone:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development